name: muiraquita_braille
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:

  opencv_4: ^1.0.0
  camera: ^0.10.5+3
  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.3
  http: ^0.13.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/

